### ISSUE TITLE
have 3 errors

### ISSUE THREAD

**Issue by ZhangKuixun** [Redwid/android-youtube-dl#3]
```
1.
    working: make: *** [/Users/zhangkuixun/.python-for...(and 93 more)  Exception in thread background thread for pid 75852:
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
        self.run()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
        self._target(*self._args, **self._kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 1540, in wrap
        fn(*args, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 2459, in background_thread
        handle_exit_code(exit_code)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 2157, in fn
        return self.command.handle_command_exit_code(exit_code)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
        raise exc
    sh.ErrorReturnCode_2: 

      RAN: /Users/zhangkuixun/Library/Android/sdk/android-ndk-r10e/ndk-build V=1


2.
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c: In function 'main':
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:74:3: error: 'for' loop initial declarations are only allowed in C99 mode
       for (int i = 0; i < argc; i++) {
       ^
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:74:3: note: use option -std=c99 or -std=gnu99 to compile your code
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:109:3: warning: passing argument 1 of 'Py_SetProgramName' from incompatible pointer type [enabled by default]
       Py_SetProgramName(L"android_python");
       ^
    In file included from /Users/zhangkuixun/.python-for-android/build/other_builds/python2-openssl/armeabi-v7a__ndk_target_21/python2/python-install/include/python2.7/Python.h:127:0,
                     from /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:3:
    /Users/zhangkuixun/.python-for-android/build/other_builds/python2-openssl/armeabi-v7a__ndk_target_21/python2/python-install/include/python2.7/pythonrun.h:22:18: note: expected 'char *' but argument is of type 'unsigned int *'
     PyAPI_FUNC(void) Py_SetProgramName(char *);
                      ^
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c: In function 'Java_org_redwid_android_youtube_dl_YoutubeDlWorker_nativeStart':
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:366:3: error: 'for' loop initial declarations are only allowed in C99 mode
       for (int i = 0; i < stringCount; i++) {
       ^
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:375:3: warning: passing argument 2 of 'main' from incompatible pointer type [enabled by default]
       main(stringCount, argv);
       ^
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:68:5: note: expected 'char **' but argument is of type 'const char **'
     int main(int argc, char *argv[]) {
         ^
    make: *** [/Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/obj/local/armeabi-v7a/objs/main/start.o] Error 1


      STDERR:

    Traceback (most recent call last):                                             
      File "/Library/Frameworks/Python.framework/Versions/3.7/bin/p4a", line 11, in <module>
        load_entry_point('python-for-android==0.6.0', 'console_scripts', 'p4a')()
      File "/Users/zhangkuixun/Downloads/download/python-for-android/pythonforandroid/toolchain.py", line 1028, in main
        ToolchainCL()
      File "/Users/zhangkuixun/Downloads/download/python-for-android/pythonforandroid/toolchain.py", line 550, in __init__
        getattr(self, args.subparser_name.replace('-', '_'))(args)
      File "/Users/zhangkuixun/Downloads/download/python-for-android/pythonforandroid/toolchain.py", line 149, in wrapper_func
        build_dist_from_args(ctx, dist, args)
      File "/Users/zhangkuixun/Downloads/download/python-for-android/pythonforandroid/toolchain.py", line 188, in build_dist_from_args
        build_recipes(build_order, python_modules, ctx)
      File "/Users/zhangkuixun/Downloads/download/python-for-android/pythonforandroid/build.py", line 617, in build_recipes
        recipe.build_arch(arch)
      File "/Users/zhangkuixun/Downloads/download/python-for-android/pythonforandroid/recipes/sdl2/__init__.py", line 41, in build_arch
        shprint(sh.ndk_build, "V=1", _env=env)
      File "/Users/zhangkuixun/Downloads/download/python-for-android/pythonforandroid/logger.py", line 176, in shprint
        for line in output:
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 863, in next
        self.wait()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 792, in wait
        self.handle_command_exit_code(exit_code)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
        raise exc
    sh.ErrorReturnCode_2: 

      RAN: /Users/zhangkuixun/Library/Android/sdk/android-ndk-r10e/ndk-build V=1


3.
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c: In function 'main':
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:74:3: error: 'for' loop initial declarations are only allowed in C99 mode
       for (int i = 0; i < argc; i++) {
       ^
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:74:3: note: use option -std=c99 or -std=gnu99 to compile your code
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:109:3: warning: passing argument 1 of 'Py_SetProgramName' from incompatible pointer type [enabled by default]
       Py_SetProgramName(L"android_python");
       ^
    In file included from /Users/zhangkuixun/.python-for-android/build/other_builds/python2-openssl/armeabi-v7a__ndk_target_21/python2/python-install/include/python2.7/Python.h:127:0,
                     from /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:3:
    /Users/zhangkuixun/.python-for-android/build/other_builds/python2-openssl/armeabi-v7a__ndk_target_21/python2/python-install/include/python2.7/pythonrun.h:22:18: note: expected 'char *' but argument is of type 'unsigned int *'
     PyAPI_FUNC(void) Py_SetProgramName(char *);
                      ^
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c: In function 'Java_org_redwid_android_youtube_dl_YoutubeDlWorker_nativeStart':
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:366:3: error: 'for' loop initial declarations are only allowed in C99 mode
       for (int i = 0; i < stringCount; i++) {
       ^
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:375:3: warning: passing argument 2 of 'main' from incompatible pointer type [enabled by default]
       main(stringCount, argv);
       ^
    /Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/jni/src/start.c:68:5: note: expected 'char **' but argument is of type 'const char **'
     int main(int argc, char *argv[]) {
         ^
    make: *** [/Users/zhangkuixun/.python-for-android/build/bootstrap_builds/sdl2-python2/obj/local/armeabi-v7a/objs/main/start.o] Error 1
```

**Comment by ZhangKuixun** [comment]
Sorry, I'm Android Developer, python is really too difficult for me.

**Comment by Redwid** [comment]
Please ask help there: https://github.com/kivy/python-for-android/issues
I've no idea what all of this errors means as well.
